### ISSUE TITLE
Add HTML syntax support

### ISSUE THREAD

**Issue by siewers** [leighlondon/eml#2]
There's a Sublime package which does more or less the same as this extension for VSCode, but it has HTML syntax support.
Would that be possible to add to this extension?
https://github.com/jacobmovingfwd/eml-syntax/blob/master/eml.sublime-syntax

**Comment by leighlondon** [comment]
Hmmm, that's a pretty good idea - there was some "accidental" highlighting of HTML when it overlapped with other syntax rules, but nothing explicit.

I've created a PR with the support in #3 but I'll need to come up with some more test fixtures and test on some different platforms over the next couple of days to fully validate it.

Thanks!

**Comment by leighlondon** [comment]
Merged the new syntax feature in with #3, and it's now been published as v0.3.1. Thanks again!

🎉
